/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module game_Beta_2 (
    input button_1,
    input button_2,
    input button_3,
    input start_button,
    input reset_button,
    input clk,
    input rst,
    output reg [14:0] led_out,
    output reg dec_score_inc,
    output reg dec_score_rst
  );
  
  
  
  reg [15:0] inputAlu_a;
  
  reg [15:0] inputAlu_b;
  
  wire [2-1:0] M_game_controlunit_level;
  wire [16-1:0] M_game_controlunit_data_goto_reg;
  wire [6-1:0] M_game_controlunit_alufn;
  wire [2-1:0] M_game_controlunit_asel;
  wire [2-1:0] M_game_controlunit_bsel;
  wire [1-1:0] M_game_controlunit_we_regfile;
  wire [4-1:0] M_game_controlunit_regfile_write_address;
  wire [4-1:0] M_game_controlunit_regfile_read_address_a;
  wire [4-1:0] M_game_controlunit_regfile_read_address_b;
  wire [1-1:0] M_game_controlunit_wdsel;
  wire [15-1:0] M_game_controlunit_led_out;
  wire [1-1:0] M_game_controlunit_dec_score_rst;
  wire [1-1:0] M_game_controlunit_dec_score_inc;
  reg [1-1:0] M_game_controlunit_button_1;
  reg [1-1:0] M_game_controlunit_button_2;
  reg [1-1:0] M_game_controlunit_button_3;
  reg [1-1:0] M_game_controlunit_start_button;
  reg [1-1:0] M_game_controlunit_reset_button;
  reg [16-1:0] M_game_controlunit_alu_read;
  reg [15-1:0] M_game_controlunit_led_in;
  game_CU_v2_10 game_controlunit (
    .clk(clk),
    .rst(rst),
    .button_1(M_game_controlunit_button_1),
    .button_2(M_game_controlunit_button_2),
    .button_3(M_game_controlunit_button_3),
    .start_button(M_game_controlunit_start_button),
    .reset_button(M_game_controlunit_reset_button),
    .alu_read(M_game_controlunit_alu_read),
    .led_in(M_game_controlunit_led_in),
    .level(M_game_controlunit_level),
    .data_goto_reg(M_game_controlunit_data_goto_reg),
    .alufn(M_game_controlunit_alufn),
    .asel(M_game_controlunit_asel),
    .bsel(M_game_controlunit_bsel),
    .we_regfile(M_game_controlunit_we_regfile),
    .regfile_write_address(M_game_controlunit_regfile_write_address),
    .regfile_read_address_a(M_game_controlunit_regfile_read_address_a),
    .regfile_read_address_b(M_game_controlunit_regfile_read_address_b),
    .wdsel(M_game_controlunit_wdsel),
    .led_out(M_game_controlunit_led_out),
    .dec_score_rst(M_game_controlunit_dec_score_rst),
    .dec_score_inc(M_game_controlunit_dec_score_inc)
  );
  wire [16-1:0] M_regfile_out_a;
  wire [16-1:0] M_regfile_out_b;
  reg [4-1:0] M_regfile_write_address;
  reg [1-1:0] M_regfile_we;
  reg [16-1:0] M_regfile_data;
  reg [4-1:0] M_regfile_read_address_a;
  reg [4-1:0] M_regfile_read_address_b;
  game_regfile_v2_11 regfile (
    .clk(clk),
    .rst(rst),
    .write_address(M_regfile_write_address),
    .we(M_regfile_we),
    .data(M_regfile_data),
    .read_address_a(M_regfile_read_address_a),
    .read_address_b(M_regfile_read_address_b),
    .out_a(M_regfile_out_a),
    .out_b(M_regfile_out_b)
  );
  wire [16-1:0] M_game_alu_out;
  wire [1-1:0] M_game_alu_z;
  wire [1-1:0] M_game_alu_v;
  wire [1-1:0] M_game_alu_n;
  wire [1-1:0] M_game_alu_err;
  reg [6-1:0] M_game_alu_alufn;
  reg [16-1:0] M_game_alu_x;
  reg [16-1:0] M_game_alu_y;
  alu16_12 game_alu (
    .clk(clk),
    .rst(rst),
    .alufn(M_game_alu_alufn),
    .x(M_game_alu_x),
    .y(M_game_alu_y),
    .out(M_game_alu_out),
    .z(M_game_alu_z),
    .v(M_game_alu_v),
    .n(M_game_alu_n),
    .err(M_game_alu_err)
  );
  wire [15-1:0] M_rom_out;
  wire [1-1:0] M_rom_shift_down;
  reg [2-1:0] M_rom_level;
  level_generator_13 rom (
    .clk(clk),
    .rst(rst),
    .level(M_rom_level),
    .out(M_rom_out),
    .shift_down(M_rom_shift_down)
  );
  
  always @* begin
    M_game_controlunit_button_1 = button_1;
    M_game_controlunit_button_2 = button_2;
    M_game_controlunit_button_3 = button_3;
    M_game_controlunit_start_button = start_button;
    M_game_controlunit_reset_button = reset_button;
    M_regfile_we = M_game_controlunit_we_regfile;
    M_regfile_write_address = M_game_controlunit_regfile_write_address;
    M_regfile_read_address_a = M_game_controlunit_regfile_read_address_a;
    M_regfile_read_address_b = M_game_controlunit_regfile_read_address_b;
    M_rom_level = M_game_controlunit_level;
    M_game_controlunit_led_in = M_rom_out;
    
    case (M_game_controlunit_asel)
      2'h0: begin
        inputAlu_a = M_regfile_out_a;
      end
      2'h1: begin
        inputAlu_a = 1'h0;
      end
      default: begin
        inputAlu_a = 1'h0;
      end
    endcase
    
    case (M_game_controlunit_bsel)
      2'h0: begin
        inputAlu_b = M_regfile_out_b;
      end
      2'h1: begin
        inputAlu_b = 1'h1;
      end
      2'h2: begin
        inputAlu_b = M_rom_out[0+2-:3];
      end
      2'h3: begin
        inputAlu_b = 4'ha;
      end
      default: begin
        inputAlu_b = 1'h0;
      end
    endcase
    M_game_alu_x = inputAlu_a;
    M_game_alu_y = inputAlu_b;
    M_game_alu_alufn = M_game_controlunit_alufn;
    M_game_controlunit_alu_read = M_game_alu_out;
    
    case (M_game_controlunit_wdsel)
      2'h1: begin
        M_regfile_data = M_game_controlunit_data_goto_reg;
      end
      default: begin
        M_regfile_data = M_game_alu_out;
      end
    endcase
    led_out = M_game_controlunit_led_out;
    dec_score_inc = M_game_controlunit_dec_score_inc;
    dec_score_rst = M_game_controlunit_dec_score_rst;
  end
endmodule
