/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module led_rom_20 (
    input [9:0] address,
    output reg [14:0] out
  );
  
  
  
  localparam LED_SEQ = 1050'h224628918a252288c8a232228c88a32228c88a32228c88a32228c88a2a228a8895112545095242519098642619118614618518614518514618518a14628548a19228a488a9242a430a86151185146145191144c45431190c4a43229098a48628a188a8642a150a8542a150a8542a150a8542a150a8542a150a8502a100a800280008000;
  
  always @* begin
    out[12+2-:3] = LED_SEQ[(address)*15+0+2-:3];
    out[9+2-:3] = LED_SEQ[(address)*15+3+2-:3];
    out[6+2-:3] = LED_SEQ[(address)*15+6+2-:3];
    out[3+2-:3] = LED_SEQ[(address)*15+9+2-:3];
    out[3+2-:3] = LED_SEQ[(address)*15+12+2-:3];
  end
endmodule
