/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module multiplier16_22 (
    input [15:0] x,
    input [15:0] y,
    input [5:0] alufn,
    output reg [15:0] s,
    output reg error
  );
  
  
  
  reg a;
  
  reg divisor;
  
  reg temp;
  
  always @* begin
    error = 1'h0;
    a = 1'h0;
    divisor = 1'h0;
    temp = 1'h0;
    
    case (alufn[0+1-:2])
      2'h0: begin
        s = x * y;
      end
      2'h1: begin
        if (y != 1'h0) begin
          s = x / y;
        end else begin
          s = x;
          error = 1'h1;
        end
      end
    endcase
  end
endmodule
