/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module level_generator_13 (
    input clk,
    input rst,
    input [1:0] level,
    output reg [14:0] out,
    output reg shift_down
  );
  
  
  
  wire [15-1:0] M_led_rom_out;
  reg [10-1:0] M_led_rom_address;
  led_rom_20 led_rom (
    .address(M_led_rom_address),
    .out(M_led_rom_out)
  );
  
  wire [10-1:0] M_address_rom_address_out;
  wire [1-1:0] M_address_shift_down;
  reg [2-1:0] M_address_level;
  clocked_address_21 address (
    .clk(clk),
    .rst(rst),
    .level(M_address_level),
    .rom_address_out(M_address_rom_address_out),
    .shift_down(M_address_shift_down)
  );
  
  always @* begin
    out = M_led_rom_out;
    M_led_rom_address = M_address_rom_address_out;
    M_address_level = level;
    shift_down = M_address_shift_down;
  end
endmodule
